### ISSUE TITLE
Please add Bot Sentry plugin

### ISSUE THREAD

**Issue by ssokolow** [flathub/im.pidgin.Pidgin#21]
I'd love to have Flatpak provide a way to sandbox my Pidgin without resorting to Firejail and keep it up to date, but I rely heavily on the [Bot Sentry](https://sourceforge.net/projects/pidgin-bs/) plugin to keep PM spam at bay on IRC.

Please consider providing it for `im.pidgin.Pidgin`.

(I'm not sure if there's a newer source than the SourceForge page. I just install the Debian or Ubuntu package so maybe pull whatever patches they're applying.)

**Comment by hfiguiere** [comment]
I think this was covered by #26

**Comment by ssokolow** [comment]
That appears to be what I was talking about in #22, judging by the URL. (<https://sourceforge.net/projects/pidgin/files/purple%20plugin%20pack/2.8.0/purple-plugin-pack-2.8.0.tar.xz>)

Given that Debian-family distros package bot sentry separately, and that it has a separate SourceForge project (<https://sourceforge.net/projects/pidgin-bs/>), I'm doubtful that this is covered by that... but I will check to see if Bot Sentry is now present in the list when I have a moment to install the Flatpak version again.

(Since these plugins are non-negotiable, I've been running mainline Ubuntu repo Pidgin under Firejail while I wait for them.)

**Comment by ssokolow** [comment]
Just checked. Bot Sentry is still not in the list of available plugins, which means I'll be staying on APT+Firejail for now.

**Comment by Pixelnarium** [comment]
I added it now. Should come with the next update when Flathub build the newest merge. These plugins are often very old. This stuff here is from 2008. Its problematic to build them especially on other architectures like ARM.

**Comment by ssokolow** [comment]
The [Ubuntu package](https://packages.ubuntu.com/jammy/pidgin-bot-sentry) has it building for amd64, arm64, armhf, ppc64el, and s390x and they also have i386 in releases that predate their sunsetting of support for 32-bit x86. Have you checked what patches they're using?

That's the approach I took when figuring out how to put together a [proposed LGOGDownloader Flatpak build](https://gist.github.com/ssokolow/26a2cc98cded622ecae43035ba0a6cfa) when everyone's "solution" for building the unmaintained HTML parser it depends on is to use or grab files from an old RHEL or SLES or use a `-legacy` package Ubuntu offers. (It turned out the AUR had a more reasonable answer.)

**Comment by Pixelnarium** [comment]
Sure, I check other Linux distribution packages for hints how to build something. But since Flatpak is another environment than the distribution package I look at, I need also understand what they do and if I need that too. This is all pretty time consuming by itself. Debugging why something fails comes on top of that.

And all that to import a horribly old and unmaintained piece of code that may or may not work with the next major version of Pidgin that is currently being developed.

**Comment by ssokolow** [comment]
Looks good so far, but, since I opened this feature request, one other plugin became necessary: [purple-googlechat](https://github.com/EionRobb/purple-googlechat) by Eion Robb, as a result of Google shutting down their XMPP interface.

I'll look into whether I need to open a feature request for that after I've slept.
