### ISSUE TITLE
Please add Purple Plugin Pack

### ISSUE THREAD

**Issue by ssokolow** [flathub/im.pidgin.Pidgin#22]
In addition to Bot Sentry (#21), the number-one thing I always apt-get for non-Flatpak'd Pidgin is [purple-plugin-pack](https://keep.imfreedom.org/pidgin/purple-plugin-pack).

It provides plugins such as the following which really make Pidgin more comfortable as a way to do IM and IRC with a unified interface:

* /exec
* IRC Helper
* IRC More
* Last Seen

Please consider providing a way to use these plugins with `im.pidgin.Pidgin`.

**Comment by hfiguiere** [comment]
I think this was covered by #26

**Comment by ssokolow** [comment]
Yep. I can confirm that the listed plugins are now available. :)
