### ISSUE TITLE
Update description on Pidgin app page

### ISSUE THREAD

**Issue by AJCxZ0** [flathub/im.pidgin.Pidgin#39]
The current brief [app page](https://flathub.org/apps/im.pidgin.Pidgin) includes

> This means that you can be chatting with friends on AIM, talking to a friend on Google Talk, and...

As a former long-time Pidgin and Instant Message user, I can attest that Pidgin could do both way back when AIM and Google Talk were available. What Pidgin [can do now](https://www.pidgin.im/plugins/) is most impressive and includes many modern chat protocols and services.

I suggest updating the description using the [current language](https://www.pidgin.im/about/) used by the project, i.e.

> Pidgin is a chat program which lets you log into accounts on multiple chat networks simultaneously. This means that you can be chatting with friends on XMPP and sitting in an IRC channel at the same time. 
> 
> Pidgin is compatible with the following chat networks out of the box: [Jabber/XMPP](https://en.wikipedia.org/wiki/XMPP), [Bonjour](https://en.wikipedia.org/wiki/Bonjour_(software)), [Gadu-Gadu](https://en.wikipedia.org/wiki/Gadu-Gadu), [IRC](https://en.wikipedia.org/wiki/Internet_Relay_Chat), [MicroFocus GroupWise Messenger](https://en.wikipedia.org/wiki/GroupWise) (formerly from Novell), [HCL Sametime](https://en.wikipedia.org/wiki/HCL_Sametime) (formerly from Lotus/IBM), [SILC](https://en.wikipedia.org/wiki/SILC_(protocol)), [SIMPLE](https://en.wikipedia.org/wiki/SIMPLE_(instant_messaging_protocol)), and [Zephyr](https://en.wikipedia.org/wiki/Zephyr_(protocol)). It can support many more with [plugins](https://www.pidgin.im/plugins/).

**Comment by Pixelnarium** [comment]
Thanks for the reminder. I updated the appdata file from the project to the newest version from the project itself.
